name: MineralBot
version: 2.1.0
main: gg.mineral.bot.bukkit.plugin.MineralBotPlugin
author: Jaiden
description: Mineral Bot Plugin
api: '1.7.10'
depend: [ packetevents ]
softdepend: [ ViaVersion, ViaRewind, ViaBackwards ]

commands:
  mineralbot:
    description: Mineral Bot Command
    permission: mineralbot.admin
    usage: /mineralbot
