plugins {
    id 'org.jetbrains.kotlin.jvm'
}
dependencies {
    compileOnly 'org.apache.logging.log4j:log4j-api:2.25.3'
    compileOnly 'org.apache.logging.log4j:log4j-core:2.25.3'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2'
    implementation project(':bot-api')
    compileOnly 'it.unimi.dsi:fastutil:8.5.18'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
    testImplementation 'org.apache.logging.log4j:log4j-api:2.25.3'
    testImplementation 'it.unimi.dsi:fastutil:8.5.18'
    testImplementation platform('org.junit:junit-bom:5.11.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

tasks.withType(Test).configureEach { useJUnitPlatform() }

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
}
repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(17)
}
